version: '3'

services:
  lambda:
    build: .
    env_file: .env
    environment:
      - PYTHONPATH=/var/task/src:/var/task/lib
      - PATH=/var/task/bin
    volumes:
      - ./src/:/var/task/src/
